Feat/norbey vasquez/seller list clients
santy289/WorkIt pull request #34
Opened 2022-03-20 06:05 UTC by nvasquezt

![image](https://user-images.githubusercontent.com/94779793/159150343-0c4372ca-1a9e-416b-b48d-c17450b72085.png)
![image](https://user-images.githubusercontent.com/94779793/159150386-a5029228-783f-4e2f-a749-036f2716df9a.png)
![image](https://user-images.githubusercontent.com/94779793/159150415-30a70e57-eba3-41ac-a4f8-bbfbb6803f1a.png)
![image](https://user-images.githubusercontent.com/94779793/159150419-ce90b188-12c6-4f32-9d1f-0b281c5ce688.png)

2022-03-20 15:57 UTC, santy289 requested changes
Mira que pasó ya que dice que borraste casi todo el package-lock.json, hay 18k de lineas borradas

- [x] Revisar el package-lock.json

2022-03-20 16:44 UTC, nvasquezt commented
> 
Buenas, cuando hice el npm install para actualizar lo del redux, quedaron 13.000 líneas, a lo mejor desacopló instancias al haberlas amarrado
![image](https://user-images.githubusercontent.com/94779793/159173041-a4b5cb18-2464-44ab-a9f8-c682b940a7b7.png)

2022-03-20 16:45 UTC, nvasquezt commented
> > 
> 
> Buenas, cuando hice el npm install para actualizar lo del redux, quedaron 13.000 líneas, a lo mejor desacopló instancias al haberlas amarrado ![image](https://user-images.githubusercontent.com/94779793/159173041-a4b5cb18-2464-44ab-a9f8-c682b940a7b7.png)

sin embargo hice pruebas y al momento no veo diferencias en el manejo del proyecto

2022-03-21 16:53 UTC, santy289 approved these changes
![ChopApproveCopApproveGIF](https://user-images.githubusercontent.com/84546929/159317372-b343143a-2e0d-4a7c-b81c-d00c3c8c8cc7.gif)

2022-03-21 21:01 UTC, merged