Fix/filter
santy289/WorkIt pull request #57
Opened 2022-04-13 02:17 UTC by julians55

![Screenshot from 2022-04-12 20-29-49](https://user-images.githubusercontent.com/99279145/163086249-55cbca23-4645-4747-b731-052d0ef5a2e0.png)

Please review, filter component changed

2022-04-14 11:35 UTC, Danatts commented on src/components/Filter/Filter.styles.scss
> +input {
Rercuerde no usar etiquetas (form, label, input, span...) para modificar estilos porque puede afectar otros componentes que tienen esas mismas etiquetas... lo mejor es que use clases

2022-04-14 20:30 UTC, julians55 commented on src/components/Filter/Filter.styles.scss
> +input {
Done!

2022-04-14 23:57 UTC, santy289 requested changes
Porfa ponga elcomponente en la page de compras, para ver como queda y luego no genere conflictos

2022-04-18 01:50 UTC, julians55 commented
> Porfa ponga elcomponente en la page de compras, para ver como queda y luego no genere conflictos

Done!
![filterinmobile](https://user-images.githubusercontent.com/99279145/163742110-0827ef08-3a16-4de1-9878-d3e1fda4ff2d.png)
![filterinwide](https://user-images.githubusercontent.com/99279145/163742112-ae12b553-d6ee-40dd-9be9-4abe44118750.png)

2022-04-18 15:38 UTC, santy289 approved these changes
![GoodFineGIF](https://user-images.githubusercontent.com/84546929/163833064-27536bd4-8743-4fc9-bdb2-1e908e3160b3.gif)

2022-04-18 15:40 UTC, merged